# Copyright [2023] Boston Dynamics AI Institute, Inc.

repos:
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.263'
    hooks:
    -   id: ruff
        args: ['--fix', '--config', 'pyproject.toml']

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  -   id: check-yaml
      args: ['--unsafe']
  -   id: check-added-large-files
      args: ['--enforce-all', '--maxkb', '200']
  -   id: check-toml
  -   id: end-of-file-fixer
  -   id: check-merge-conflict
  -   id: check-executables-have-shebangs
  -   id: check-shebang-scripts-are-executable

-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
        language_version: python3.9
        args: ['--config', 'pyproject.toml']
        verbose: true

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.2.0
    hooks:
    -   id: mypy
        pass_filenames: false
        additional_dependencies:
        - types-protobuf
        - types-requests
        - types-simplejson
        - types-ujson
        - types-PyYAML
        - types-toml
        - types-six

- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 3.0.0
  hooks:
  -  id: forbid-binary
