# Copyright [2023] Boston Dynamics AI Institute, Inc.

repos:
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.263'
    hooks:
    -   id: ruff
        args: ['--fix', '--config', 'pyproject.toml']
        exclude: 'dreamerv3/.*|grpc_infra/.*'

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: end-of-file-fixer
        exclude: 'dreamerv3/.*|grpc_infra/.*'
    -   id: trailing-whitespace
        exclude: 'dreamerv3/.*|grpc_infra/.*'
    -   id: check-yaml
        exclude: 'dreamerv3/.*|grpc_infra/.*'
    -   id: check-added-large-files
        exclude: 'dreamerv3/.*|grpc_infra/.*'
    -   id: check-toml
        exclude: 'dreamerv3/.*|grpc_infra/.*'

-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
        language_version: python3.9
        args: ['--config', 'pyproject.toml']
        exclude: 'dreamerv3/.*|grpc_infra/.*'
        verbose: true

# -   repo: https://github.com/pre-commit/mirrors-mypy
#     rev: v1.2.0
#     hooks:
#     -   id: mypy
#         pass_filenames: false
#         additional_dependencies:
#         - types-protobuf
#         - types-requests
#         - types-simplejson
#         - types-ujson
#         - types-PyYAML
#         - types-toml
#         - types-six
