# Copyright (c) 2023 Boston Dynamics AI Institute LLC. All rights reserved.

# @package _global_

defaults:
  - /habitat: habitat_config_base
  - /habitat/task: pointnav
  - /habitat/dataset/pointnav: hm3d
  - /habitat/simulator/agents@habitat.simulator.agents.main_agent: depth_agent
  - _self_

habitat:
  environment:
    max_episode_steps: 500
  simulator:
    agents:
      main_agent:
        height: 0.88
        radius: 0.18
        sim_sensors:
          depth_sensor:
            width: 640
            height: 480
            hfov: 79
            min_depth: 0.5
            max_depth: 5.0
            position: [0, 0.88, 0]
    habitat_sim_v0:
      gpu_device_id: 0
      allow_sliding: False
