# Copyright [2023] Boston Dynamics AI Institute, Inc.

name: VLFM CI
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  vlfm_main_build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    container:
      image: ghcr.io/bdaiinstitute/bdaii_vlfm:main
    steps:
    - uses: actions/checkout@v3
    - name: Pytest
      run: |
        pytest
